# Generated by Django 2.2.6 on 2021-02-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0004_auto_20210225_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abirimparametre',
            name='birim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='sbs.Abirim', verbose_name='Birim'),
        ),
    ]
