# Generated by Django 2.2.6 on 2021-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0007_auto_20210225_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adosya',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Tanımı'),
        ),
    ]
