# Generated by Django 2.2.6 on 2021-02-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0008_auto_20210225_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adosya',
            name='name',
        ),
    ]
