# Generated by Django 2.2.6 on 2021-02-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0009_remove_adosya_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adosya',
            name='klasor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='sbs.Aklasor'),
        ),
    ]
