# Generated by Django 2.2.6 on 2021-02-25 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0010_auto_20210225_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adosyaparametre',
            name='type',
        ),
    ]
