# Generated by Django 2.2.6 on 2021-02-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0012_auto_20210225_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aevrak',
            name='name',
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t1'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t10',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t10'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t11',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t11'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t12'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t13',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t13'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t14',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t14'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t15',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t15'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t16',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t16'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t2'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t3'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t4'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t5'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t6'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t7'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t8'),
        ),
        migrations.AddField(
            model_name='aevrak',
            name='t9',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='t9'),
        ),
    ]
