# Generated by Django 2.2.6 on 2021-03-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sbs', '0015_remove_aevrak_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aevrak',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
